# arxivの学問領域の指定
subject: 'cat:stat.* OR cat:econ.*'

# 検索キーワード
keywords:
        high dimension: 3
        treatment effects: 3
        doubly robust: 2
        causal: 2
        high-dimensional: 2
        robust: 1

# 通知の閾値
score_threshold: 0
